services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - shared-net
    volumes:
      - ./.env:/.env  # map local .env into /app/.env inside container

networks:
  shared-net:
    external: true
  isolated_app_network:
    driver: bridge
