# APP NAME
spring.application.name=product-store

# MY SQL DATA SOURCE
application.properties file:

spring.datasource.url=jdbc:mysql://localhost:3307/product_store
#spring.datasource.url=jdbc:mysql://mysql:3306/product_store
spring.datasource.username=root
spring.datasource.password=debezium
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=product_store

# Error Handling
server.error.include-message=always

# Spring Cache configuration
spring.cache.type=redis

# Redis configuration
spring.data.redis.host=localhost
#spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.redis.time-to-live=900000

# LOGGING AND HEALTH
# Set global log level
logging.level.root=INFO

# Set log level for your application package
logging.level.com.example=DEBUG

# Customize log format (console output)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n


# Expose only health and info endpoints
management.endpoints.web.exposure.include=health,info

# Enable health endpoint
management.endpoint.health.show-details=always

# Speed up hibernate insertions
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.kafka.bootstrap-servers=localhost:29092
#spring.kafka.bootstrap-servers=kafka:9092


# Consumer group ID
spring.kafka.consumer.group-id=order-service-consumer
# SERIALIZERS
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# DESERIALIZERS
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.auto-offset-reset=earliest

# ignore unknown json payload field
spring.jackson.deserialization.fail-on-unknown-properties=true
